In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

random.seed(777)  # for reproducibility
learning_rate = 0.001
batch_size = 4000
training_epochs = 100
nb_classes = 16
drop_rate = 0.3

In [2]:
xy = np.loadtxt('MIMO_2_15dB_NoC_16.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 1:13]
y_data = xy[:, -4:]

print(x_data.shape, y_data.shape)
print(x_data[0])

(1600000, 12) (1600000, 4)
[ 1.9850256  -0.03969418 -1.2056918   2.735528    0.38018808  1.2967526
 -1.5972459   0.6096486   0.22540106 -0.9246753  -0.30659586  0.24227208]


In [3]:
# Convert y_data to y_bit
i=1
y_merge = []
while i <= y_data.shape[0]:
    temp = "".join(str(_) for _ in y_data[i-1,:])
    y_merge.append(temp)
    i = i + 1

encoder = LabelEncoder()
encoder.fit(y_merge)
y_bit = encoder.transform(y_merge)
y_bit = y_bit.reshape(-1, 1)
print(y_bit)

[[ 3]
 [ 3]
 [ 3]
 ...
 [12]
 [12]
 [12]]


In [4]:
# Convert y_data to one_hot
y_one_hot = tf.keras.utils.to_categorical(y_bit, nb_classes)
print("one_hot:", y_one_hot)

one_hot: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
tf.model = tf.keras.Sequential()
# Glorot normal initializer, also called Xavier normal initializer.
# see https://www.tensorflow.org/api_docs/python/tf/initializers

In [6]:
tf.model.add(tf.keras.layers.Dense(input_dim=x_data.shape[1], units=768, kernel_regularizer=tf.keras.regularizers.l2(0.001), activation='relu'))
tf.model.add(tf.keras.layers.Dropout(drop_rate))
tf.model.add(tf.keras.layers.Dense(units=384, kernel_regularizer=tf.keras.regularizers.l2(0.001), activation='relu'))
tf.model.add(tf.keras.layers.Dropout(drop_rate))
tf.model.add(tf.keras.layers.Dense(units=192, kernel_regularizer=tf.keras.regularizers.l2(0.001), activation='relu'))
tf.model.add(tf.keras.layers.Dropout(drop_rate))
tf.model.add(tf.keras.layers.Dense(units=nb_classes, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy',
                 optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate), metrics=['accuracy'])
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 768)               9984      
_________________________________________________________________
dropout (Dropout)            (None, 768)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 384)               295296    
_________________________________________________________________
dropout_1 (Dropout)          (None, 384)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 192)               73920     
_________________________________________________________________
dropout_2 (Dropout)          (None, 192)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 16)                3

In [ ]:
history = tf.model.fit(x_data, y_one_hot, batch_size=batch_size , epochs=training_epochs)

Epoch 1/100
400/400 [==============================] - 3s 5ms/step - loss: 1.1571 - accuracy: 0.7153
Epoch 2/100
400/400 [==============================] - 2s 5ms/step - loss: 0.6820 - accuracy: 0.8379
Epoch 3/100
400/400 [==============================] - 2s 5ms/step - loss: 0.6241 - accuracy: 0.8532
Epoch 4/100
400/400 [==============================] - 2s 5ms/step - loss: 0.5915 - accuracy: 0.8623
Epoch 5/100
400/400 [==============================] - 2s 5ms/step - loss: 0.5678 - accuracy: 0.8689
Epoch 6/100
400/400 [==============================] - 2s 5ms/step - loss: 0.5471 - accuracy: 0.8748
Epoch 7/100
400/400 [==============================] - 2s 5ms/step - loss: 0.5307 - accuracy: 0.8782
Epoch 8/100
400/400 [==============================] - 2s 5ms/step - loss: 0.5178 - accuracy: 0.8807
Epoch 9/100
400/400 [==============================] - 2s 5ms/step - loss: 0.5073 - accuracy: 0.8823
Epoch 10/100
400/400 [==============================] - 2s 5ms/step - loss: 0.4978 - accura

400/400 [==============================] - 2s 5ms/step - loss: 0.3973 - accuracy: 0.8905
Epoch 82/100
400/400 [==============================] - 2s 5ms/step - loss: 0.3967 - accuracy: 0.8906
Epoch 83/100
400/400 [==============================] - 2s 5ms/step - loss: 0.3978 - accuracy: 0.8905
Epoch 84/100
400/400 [==============================] - 2s 5ms/step - loss: 0.3981 - accuracy: 0.8902
Epoch 85/100
400/400 [==============================] - 2s 5ms/step - loss: 0.3970 - accuracy: 0.8907
Epoch 86/100
400/400 [==============================] - 2s 5ms/step - loss: 0.3969 - accuracy: 0.8907
Epoch 87/100
400/400 [==============================] - 2s 5ms/step - loss: 0.3966 - accuracy: 0.8909
Epoch 88/100
400/400 [==============================] - 2s 5ms/step - loss: 0.3958 - accuracy: 0.8906
Epoch 89/100
400/400 [==============================] - 2s 5ms/step - loss: 0.3961 - accuracy: 0.8905
Epoch 90/100
400/400 [==============================] - 2s 5ms/step - loss: 0.3962 - accuracy: 

In [ ]:
# 모델 손실 함수 시각화
from jupyterthemes import jtplot
jtplot.style(theme='monokai')

plt.plot(history.history['loss'], 'b-', label='loss')
#plt.plot(history.history['val_loss'], 'r-', label='val_loss')
plt.title('Model loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

In [ ]:
# 모델 정확도 시각화
plt.plot(history.history['accuracy'], 'g-', label='accuracy')
#plt.plot(history.history['val_accuracy'], 'r-', label='val_accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

In [ ]:
# Full x_data test
test_data = np.loadtxt('MIMO_2_15dB_NoC_16_test.csv', delimiter=',', dtype=np.float32)
x_test_data = test_data[:, 1:13]
y_test_data = test_data[:, -4:]
print(x_test_data.shape, y_test_data.shape)

In [ ]:
# Convert y_test_data to y_test_bit
i=1
y_test_merge = []
while i <= y_test_data.shape[0]:
    temp2 = "".join(str(_) for _ in y_test_data[i-1,:])
    y_test_merge.append(temp2)
    i = i + 1

encoder = LabelEncoder()
encoder.fit(y_test_merge)
y_test_bit = encoder.transform(y_test_merge)
y_test_bit = y_test_bit.reshape(-1, 1)
print(y_test_bit)

In [ ]:
# Convert y_data to one_hot
y_test_one_hot = tf.keras.utils.to_categorical(y_test_bit, nb_classes)
print("one_hot:", y_test_one_hot)

In [ ]:
evaluation = tf.model.evaluate(x_test_data, y_test_one_hot)
print('loss: ', evaluation[0])
print('accuracy', evaluation[1])

In [ ]:
#pre_error_cnt = 0
predict_x = tf.model.predict(x_test_data) 
pred = np.argmax(predict_x,axis=1)
#for p, y in zip(pred, y_test_bit.flatten()):
    #print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))
    #if p != int(y):
        #pre_error_cnt += 1
#print("Prediction Error Count : ", pre_error_cnt)

In [ ]:
res_pred = pred.reshape(y_test_data.shape[0], 1)
error_cnt = 0
error = 0
for i in range(0, y_test_data.shape[0]):
    if res_pred[i] != y_test_bit[i]:
        #print("False : {}".format(i))
        #print("[{}] data : {}".format(i, y_test_data[i]))
        error += 1
        for n in range(0, y_test_data.shape[0], int(y_test_data.shape[0]/nb_classes)):
            if y_test_bit[n] == res_pred[i]:
                #print("[{}] pred data: {}".format(n, y_test_data[n]))
                bit_error = 0
                for m in range(0, y_test_data.shape[1]): 
                    if y_test_data[i, m] != y_test_data[n, m]:
                        bit_error += 1
                        error_cnt += 1
                #print("bit error count : ", bit_error)
                break
print("Error : {}".format(error))
print("Error Count: {}".format(error_cnt))

In [ ]:
BER = (error_cnt)/(y_test_data.shape[0]*2*2)
print("BER: {}".format(BER))